/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuggestRouteImport } from './routes/suggest'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FinderRouteImport } from './routes/finder'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceIdRouteImport } from './routes/service.$id'
import { Route as PlanIdRouteImport } from './routes/plan.$id'
import { Route as ServiceIdIntakeRouteImport } from './routes/service.$id_.intake'
import { Route as PlanIdPrintRouteImport } from './routes/plan.$id.print'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestRoute = SuggestRouteImport.update({
  id: '/suggest',
  path: '/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FinderRoute = FinderRouteImport.update({
  id: '/finder',
  path: '/finder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceIdRoute = ServiceIdRouteImport.update({
  id: '/service/$id',
  path: '/service/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanIdRoute = PlanIdRouteImport.update({
  id: '/plan/$id',
  path: '/plan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceIdIntakeRoute = ServiceIdIntakeRouteImport.update({
  id: '/service/$id_/intake',
  path: '/service/$id/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanIdPrintRoute = PlanIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => PlanIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/finder': typeof FinderRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/saved': typeof SavedRoute
  '/services': typeof ServicesRoute
  '/suggest': typeof SuggestRoute
  '/terms': typeof TermsRoute
  '/plan/$id': typeof PlanIdRouteWithChildren
  '/service/$id': typeof ServiceIdRoute
  '/plan/$id/print': typeof PlanIdPrintRoute
  '/service/$id/intake': typeof ServiceIdIntakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/finder': typeof FinderRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/saved': typeof SavedRoute
  '/services': typeof ServicesRoute
  '/suggest': typeof SuggestRoute
  '/terms': typeof TermsRoute
  '/plan/$id': typeof PlanIdRouteWithChildren
  '/service/$id': typeof ServiceIdRoute
  '/plan/$id/print': typeof PlanIdPrintRoute
  '/service/$id/intake': typeof ServiceIdIntakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/finder': typeof FinderRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/saved': typeof SavedRoute
  '/services': typeof ServicesRoute
  '/suggest': typeof SuggestRoute
  '/terms': typeof TermsRoute
  '/plan/$id': typeof PlanIdRouteWithChildren
  '/service/$id': typeof ServiceIdRoute
  '/plan/$id/print': typeof PlanIdPrintRoute
  '/service/$id_/intake': typeof ServiceIdIntakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/finder'
    | '/help'
    | '/privacy'
    | '/report'
    | '/saved'
    | '/services'
    | '/suggest'
    | '/terms'
    | '/plan/$id'
    | '/service/$id'
    | '/plan/$id/print'
    | '/service/$id/intake'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/finder'
    | '/help'
    | '/privacy'
    | '/report'
    | '/saved'
    | '/services'
    | '/suggest'
    | '/terms'
    | '/plan/$id'
    | '/service/$id'
    | '/plan/$id/print'
    | '/service/$id/intake'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/finder'
    | '/help'
    | '/privacy'
    | '/report'
    | '/saved'
    | '/services'
    | '/suggest'
    | '/terms'
    | '/plan/$id'
    | '/service/$id'
    | '/plan/$id/print'
    | '/service/$id_/intake'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  FinderRoute: typeof FinderRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRoute
  SavedRoute: typeof SavedRoute
  ServicesRoute: typeof ServicesRoute
  SuggestRoute: typeof SuggestRoute
  TermsRoute: typeof TermsRoute
  PlanIdRoute: typeof PlanIdRouteWithChildren
  ServiceIdRoute: typeof ServiceIdRoute
  ServiceIdIntakeRoute: typeof ServiceIdIntakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggest': {
      id: '/suggest'
      path: '/suggest'
      fullPath: '/suggest'
      preLoaderRoute: typeof SuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finder': {
      id: '/finder'
      path: '/finder'
      fullPath: '/finder'
      preLoaderRoute: typeof FinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$id': {
      id: '/service/$id'
      path: '/service/$id'
      fullPath: '/service/$id'
      preLoaderRoute: typeof ServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$id': {
      id: '/plan/$id'
      path: '/plan/$id'
      fullPath: '/plan/$id'
      preLoaderRoute: typeof PlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$id_/intake': {
      id: '/service/$id_/intake'
      path: '/service/$id/intake'
      fullPath: '/service/$id/intake'
      preLoaderRoute: typeof ServiceIdIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$id/print': {
      id: '/plan/$id/print'
      path: '/print'
      fullPath: '/plan/$id/print'
      preLoaderRoute: typeof PlanIdPrintRouteImport
      parentRoute: typeof PlanIdRoute
    }
  }
}

interface PlanIdRouteChildren {
  PlanIdPrintRoute: typeof PlanIdPrintRoute
}

const PlanIdRouteChildren: PlanIdRouteChildren = {
  PlanIdPrintRoute: PlanIdPrintRoute,
}

const PlanIdRouteWithChildren =
  PlanIdRoute._addFileChildren(PlanIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  FinderRoute: FinderRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRoute,
  SavedRoute: SavedRoute,
  ServicesRoute: ServicesRoute,
  SuggestRoute: SuggestRoute,
  TermsRoute: TermsRoute,
  PlanIdRoute: PlanIdRouteWithChildren,
  ServiceIdRoute: ServiceIdRoute,
  ServiceIdIntakeRoute: ServiceIdIntakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
